---
output: word_document
---
# Module 4 - Assignment 2
## Pierce, Michaela
### Data Cleansing


```{r}
library(tidyverse)


```

```{r}
library(readxl) 
CustomerChurn <- read_excel("CustomerChurn.xlsx",  
col_types = c("text", "text", "text",  
"text", "numeric", "text", "text",  
"text", "text", "text", "text", "text",  
"text", "text", "text", "text", "text",  
"numeric", "numeric", "text"))
```

#### Cleaning Missing Data

```{r}
summary(CustomerChurn)  
```



```{r}
CustomerChurn2 <-  mutate(CustomerChurn,MonthlyCharges = replace(MonthlyCharges, 
is.nan(MonthlyCharges), median(MonthlyCharges, na.rm = TRUE)))
CustomerChurn2 <- mutate(CustomerChurn2, TotalCharges = replace(TotalCharges, is.na(TotalCharges), mean(TotalCharges, na.rm = TRUE)))
CustomerChurn2 <- mutate(CustomerChurn2, PaymentMethod = replace(PaymentMethod, is.na(PaymentMethod), "ElectronicCheck"))

# Create a new dataframe CustomerChurn3
CustomerChurn3 <- CustomerChurn2 %>%
  select(PaymentMethod, MonthlyCharges, TotalCharges)

# Print the dataframe CustomerChurn3
print(CustomerChurn3)



boxplot(CustomerChurn2$tenure)$out 



outliers <- boxplot(CustomerChurn2$tenure)$out 
CustomerChurn2[which(CustomerChurn2$tenure %in% outliers),]


CustomerChurn3 <- CustomerChurn2[-which(CustomerChurn2$tenure %in% outliers),] 
boxplot(CustomerChurn3$tenure)



```


















