# Module 5 - Assignment 2
## Pierce, Michaela
### More Data Wrangling


```{r}
# Load necessary packages
library(tidyverse)


# Import tuition_cost.csv
tuition_data <- read_csv("tuition_cost.csv")

```


```{r}
head(tuition_data)
```

---


### Part 1 - Creating tidy data using tidyr



```{r}
# Pivoting to create tidy data
Tuition <- tuition_data %>%
  pivot_longer(cols = c(`2017`, `2018`, `2019`, `2020`), names_to = "Year", values_to = "tuition") %>%
  separate(tuition, into = c("InState", "OutState"), sep = "/") %>%
  mutate(across(c(InState, OutState), as.numeric)) %>%
  mutate(across(c(InState, OutState), ~gsub("\\.00", "", .)))


Tuition

```

---



### Part 2 - North Carolina Schools


```{r}
# NC PUBLIC SCHOOLS, 4 YR, IN STATE TUITION

# Filter public, 4-year universities in North Carolina
Public_NC <- filter(Tuition, state == "North Carolina" & type == "Public" & degree_length == "4 Year")

# Convert InState column to numeric
Public_NC$InState <- as.numeric(Public_NC$InState)

# Create scatterplot
ggplot(Public_NC, aes(x = Year, y = InState, color = name)) +
  geom_point() +
  labs(title = "In-State Tuition for North Carolina Schools",
       x = "Year",
       y = "Cost in $") +
  theme(legend.position = "right") +
  guides(color = guide_legend(title=NULL)) +
  theme(axis.text.y = element_text(size = 8)) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 1))

```
```{r}

# PUBLIC UNC SCHOOLS, 4  YR, IN STATE TUITION

Public_UNC<- filter(Tuition,grepl("University of North Carolina",name)) 

# Convert InState column to numeric
Public_UNC$InState <- as.numeric(Public_UNC$InState)

# Create scatterplot
ggplot(Public_UNC, aes(x = Year, y = InState, color = name)) +
  geom_point() +
  labs(title = "In-State Tuition for UNC Schools",
       x = "Year",
       y = "Cost in $") +
  theme(legend.position = "bottom") +
  guides(color = guide_legend(nrow = 4, title=NULL)) +
  theme(axis.text.y = element_text(size = 8)) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 1))

```


---


### Part 3 - Additional Universities

```{r}

# CO PUBLIC SCHOOLS, 4 YR, OUT OF STATE TUITION
Public_CO <- filter(Tuition,grepl("University of Colorado",name)) 

# Convert OutState column to numeric
Public_CO$OutState <- as.numeric(Public_CO$OutState)

# Create scatterplot
ggplot(Public_CO, aes(x = Year, y = OutState, color = name)) +
  geom_point() +
  labs(title = "Out of State Tuition for Colorado Schools",
       x = "Year",
       y = "Cost in $") +
  theme(legend.position = "bottom") +
  guides(color = guide_legend(nrow = 4, title=NULL)) +
  theme(axis.text.y = element_text(size = 8)) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 1))



################################################################################


# SC PUBLIC SCHOOLS, 2 YR, IN STATE TUITION
Public_SC <- filter(Tuition, state == "South Carolina" & type == "Public" & degree_length == "2 Year")

# Convert InState column to numeric
Public_SC$InState <- as.numeric(Public_SC$InState)



# Create scatterplot
ggplot(Public_SC, aes(x = Year, y = InState, color = name)) +
  geom_point() +
  labs(title = "In-State Tuition for South Carolina Schools",
       x = "Year",
       y = "Cost in $") +
  theme(legend.position = "bottom") +
  guides(color = guide_legend(nrow = 7, title=NULL)) + 
  theme(axis.text.y = element_text(size = 8)) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 1))


```



